### ISSUE TITLE
Build failed with an exception. Execution failed for task ':processArmv7DebugManifest'.

### ISSUE THREAD

**Issue by klochko7** [dpa99c/cordova-diagnostic-plugin#214] opened 2017-06-14 08:44 UTC
Hi all ! Could anyone suggest please how to fix such error ..

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value val
ue=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:2
7:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] Androi
dManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element a
t AndroidManifest.xml:25:5-27:34 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

See http://g.co/androidstudio/manifest-merger for more information about the man
ifest merger.

:processArmv7DebugManifest FAILED

BUILD FAILED

Total time: 28.11 secs

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\tmp\ionic2\ezpart-mobile-svn\platforms\android\AndroidManifest.xml:27:9-31 Er
ror:
        Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [c
om.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] Androi
dManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element a
t AndroidManifest.xml:25:5-27:34 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value val
ue=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:2
7:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] Androi
dManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element a
t AndroidManifest.xml:25:5-27:34 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by dpa99c** [comment] 2017-06-14 09:03
Exact duplicate of #212

**Closed by dpa99c** 2017-06-14 09:03 UTC
