### ISSUE TITLE
Build Error need assistence!

### ISSUE THREAD

**Issue by daniele777** [dpa99c/cordova-diagnostic-plugin#281] opened 2018-03-05 06:29 UTC
After an install an plugin support gradle still have a problem.. 
name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/project/build/intermediates/res/merged/release/values-v24/values-v24.xml:4 : AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/opt/android-sdk/build-tools/27.0.2/aapt'' finished with non-zero exit value 1

Thx

**Comment by dpa99c** [comment] 2018-03-05 08:44
This is an exact duplicate of #280 in which I explained the cause of the issue and that it's not directly caused by this plugin.

Please don't open another duplicate issue or you will be banned.

**Closed by dpa99c** 2018-03-05 08:44 UTC
