### ISSUE TITLE
latest version 4.0.8 build error on phonegap 

### ISSUE THREAD

**Issue by dizzlr** [dpa99c/cordova-diagnostic-plugin#309] opened 2018-05-31 23:11 UTC
latest version 4.0.8 build error on phonegap 
when remove cordova.plugins.diagnostic plugin build end successfully 

phonegap cli version  cli-6.5.0 

![capture](https://user-images.githubusercontent.com/22053064/40812921-a8fbc522-6538-11e8-8ce9-f85c834ecf8e.PNG)

this phonegap log 
-----------------------------------------------------------------------
Build Date: 2018-05-31 23:04:38 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-sms-plugin" via npm
Installing "cordova-sms-plugin" at "0.1.11" for android
Fetching plugin "cordova-plugin-call-number" via npm
Installing "cordova-plugin-call-number" at "1.0.1" for android
Fetching plugin "cordova-plugin-googleplayservices" via npm
Installing "cordova-plugin-googleplayservices" at "19.0.3" for android
Fetching plugin "cordova-plugin-camera@~2.1.1" via npm
Installing "cordova-plugin-camera" at "2.1.1" for android
Fetching plugin "cordova-plugin-media-capture@~1.2.0" via npm
Installing "cordova-plugin-media-capture" at "1.2.0" for android
Fetching plugin "cordova-plugin-file@^4.0.0" via npm
Installing "cordova-plugin-file" at "4.3.3" for android
Fetching plugin "cordova-plugin-compat@^1.0.0" via npm
Installing "cordova-plugin-compat" at "1.2.0" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-console@~1.0.2" via npm
Installing "cordova-plugin-console" at "1.0.7" for android
Fetching plugin "cordova-plugin-device@~1.1.1" via npm
Installing "cordova-plugin-device" at "1.1.7" for android
Fetching plugin "cordova-plugin-device-motion@~1.2.0" via npm
Installing "cordova-plugin-device-motion" at "1.2.5" for android
Fetching plugin "cordova-plugin-device-orientation@~1.0.2" via npm
Installing "cordova-plugin-device-orientation" at "1.0.7" for android
Fetching plugin "cordova-plugin-dialogs@~1.2.0" via npm
Installing "cordova-plugin-dialogs" at "1.2.1" for android
Plugin "cordova-plugin-file" already installed on android. Making it top-level.
Fetching plugin "cordova-plugin-file-transfer@~1.5.0" via npm
Installing "cordova-plugin-file-transfer" at "1.5.1" for android
Plugin dependency "cordova-plugin-file@4.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "4.0.1" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.3.0
Skipping 'cordova-plugin-geolocation' for android
Fetching plugin "cordova.plugins.diagnostic@~4.0.6" via npm
Installing "cordova.plugins.diagnostic" at "4.0.8" for android
Subproject Path: CordovaLib
Fetching plugin "uk.co.workingedge.phonegap.plugin.launchnavigator" via npm
Installing "uk.co.workingedge.phonegap.plugin.launchnavigator" at "4.2.0" for android
Fetching plugin "cordova-plugin-actionsheet@2" via npm
Installing "cordova-plugin-actionsheet" at "2.3.3" for android
Plugin dependency "cordova-plugin-dialogs@1.2.1" already fetched, using that version.
Dependent plugin "cordova-plugin-dialogs" already installed on android.
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-spinner" via npm
Installing "cordova-plugin-spinner" at "1.1.0" for android
Fetching plugin "cordova-plugin-globalization@~1.0.3" via npm
Installing "cordova-plugin-globalization" at "1.0.9" for android
Fetching plugin "cordova-plugin-inappbrowser@~1.3.0" via npm
Installing "cordova-plugin-inappbrowser" at "1.3.0" for android
Fetching plugin "cordova-plugin-media@~2.2.0" via npm
Installing "cordova-plugin-media" at "2.2.0" for android
Plugin dependency "cordova-plugin-file@4.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Fetching plugin "cordova-plugin-network-information@~1.2.0" via npm
Installing "cordova-plugin-network-information" at "1.2.1" for android
Fetching plugin "cordova-plugin-statusbar@~2.1.2" via npm
Installing "cordova-plugin-statusbar" at "2.1.3" for android
Fetching plugin "cordova-plugin-vibration@~2.1.0" via npm
Installing "cordova-plugin-vibration" at "2.1.6" for android
Fetching plugin "cordova-plugin-whitelist@~1.2.1" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-social-message" via npm
Installing "cordova-plugin-social-message" at "0.4.0" for android
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:26.+
cordova.system.library.2=com.android.support:appcompat-v7:26.+
cordova.system.library.3=com.squareup.okhttp3:okhttp:3+
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
Running command: /project/gradlew cdvBuildDebug -b /project/build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_n9bllnzuf5i1by8v6m7bnbm3.run(/project/build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportAnimatedVectorDrawable2610Library
:prepareComAndroidSupportAppcompatV72610Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareComAndroidSupportSupportVectorDrawable2610Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources/project/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
/project/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.377 secs
Command finished with error code 1: /project/gradlew cdvBuildDebug,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
/project/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by dpa99c** [comment] 2018-06-01 06:03
Duplicate of #240

**Closed by dpa99c** 2018-06-01 06:03 UTC

**Comment by dizzlr** [comment] 2018-06-01 11:10
hay i am use version plugin name="cordova.plugins.diagnostic" spec="~3.6.8" / but still have build error 

what should id do now :(
this my config  file
--------------------------------------------
```
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="com.mtech.nathealth" version="1.0.1" versionCode = "10001">
  <name>NatHealth</name>
  <description>NatHealth App</description>
  <author href="http://fikrgroup.com/" email="info@thm.com">thm projects.</author>
  <content src="index.html"/>
  <platform name="android" />


  <preference name="DisallowOverscroll" value="true"/>
  <preference name="permissions" value="none"/>
  <preference name="orientation" value="default"/>
  <preference name="target-device" value="universal"/>
  <preference name="fullscreen" value="false"/>
  <preference name="webviewbounce" value="true"/>
  <preference name="prerendered-icon" value="true"/>
  <preference name="stay-in-webview" value="false"/>
  <preference name="detect-data-types" value="true"/>
  <preference name="exit-on-suspend" value="false"/>
  <preference name="phonegap-version" value="cli-7.0.1" />

  <preference name="disable-cursor" value="false"/>
  <preference name="android-minSdkVersion" value="20"/>
  <preference name="android-installLocation" value="auto"/>
  <preference name="android-build-tool" value="gradle" />

  <plugin name="cordova-plugin-camera" source="npm" spec="~2.1.1"/>
  <plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-console" source="npm" spec="~1.0.2"/>

  <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1"/>
  <plugin name="cordova-plugin-device-motion" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-device-orientation" source="npm" spec="~1.0.2"/>
  <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0"/>
  <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1"/>
  <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0"/>
  <plugin name="cordova-plugin-geolocation" source="npm" />

  <plugin name="cordova.plugins.diagnostic" spec="~3.6.8" />

  <plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" source="npm" />
  <plugin name="cordova-plugin-spinner" source="npm" />
  <gap:plugin name="cordova-sms-plugin" source="npm" />
  <gap:plugin name="cordova-plugin-call-number" source="npm" />

  <plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.3"/>
  <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0"/>
  <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0"/>
  <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0"/>

  <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2"/>
  <plugin name="cordova-plugin-vibration" source="npm" spec="~2.1.0"/>
  <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1"/>
  <plugin name="cordova-plugin-social-message" source="npm"/>

  <gap:plugin name="cordova-plugin-googleplayservices" source="npm" />
 
  <icon src="icon.png"/>
  <icon platform="android" qualifier="ldpi" src="res/icons/android/icon-36-ldpi.png"/>
  <icon platform="android" qualifier="mdpi" src="res/icons/android/icon-48-mdpi.png"/>
  <icon platform="android" qualifier="hdpi" src="res/icons/android/icon-72-hdpi.png"/>
  <icon platform="android" qualifier="xhdpi" src="res/icons/android/icon-96-xhdpi.png"/>
  <icon platform="android" qualifier="xxhdpi" src="res/icons/android/icon-144-xxhdpi.png"/>
  <icon platform="android" qualifier="xxxhdpi" src="res/icons/android/icon-192-xxxhdpi.png"/>
  <splash src="splash.png" />
  <splash platform="android" qualifier="ldpi" src="res/screens/android/screen-ldpi-portrait.png" />
  <splash platform="android" qualifier="mdpi" src="res/screens/android/screen-mdpi-portrait.png" />
  <splash platform="android" qualifier="hdpi" src="res/screens/android/screen-hdpi-portrait.png" />
  <splash platform="android" qualifier="xhdpi" src="res/screens/android/screen-xhdpi-portrait.png" />
  <platform name="android">
    <preference name="android-minSdkVersion" value="20" />
    <preference name="android-targetSdkVersion" value="23" />
  </platform>

  <preference name="SplashScreenDelay" value="2000" />
  <preference name="AutoHideSplashScreen" value="true" />
  <preference name="FadeSplashScreen" value="false"/>
  <preference name="SplashMaintainAspectRatio" value="true" />
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <preference name="PWEnablePhoneStatePermission" value="false" />
  <allow-navigation href="*"/>
  <access origin="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>

</widget>
```
