### ISSUE TITLE
Not working in Windows Phone 8.1

### ISSUE THREAD

**Issue by ashvin777** [dpa99c/cordova-diagnostic-plugin#76] opened 2016-05-27 13:00 UTC
I am getting below error in windowsPhone 8.1

` Exception calling native with command :: Diagnostic :: isLocationEnabled ::exception=TypeError: Object doesn't support property or method 'requestAccessAsync'`

**Comment by dpa99c** [comment] 2016-05-27 13:03
This is an exact duplicate of #73 - please read my explanation in that issue as to why it was closed

**Closed** 2016-05-28 10:19 UTC
Labels: duplicate
