### ISSUE TITLE
Restoring plugin through `cordova prepare` command fails

### ISSUE THREAD

**Issue by mark-veenstra** [dpa99c/cordova-diagnostic-plugin#245] opened 2017-10-27 09:36 UTC
When I have the plugin dependency defined into `package.json`  as follows:

```json
{
  "name": "myApp",
  "version": "1.0.0",
  "description": "myApp description",
  "dependencies": {
    "cordova.plugins.diagnostic": "3.7.1"
  },
  "devDependencies": {
  },
  "scripts": {
  },
  "cordova": {
    "platforms": [
      "browser",
      "android",
      "ios"
    ],
    "plugins": {
      "cordova.plugins.diagnostic": {}
     }
  }
}
```

and in `config.xml` as follows:

```xml
<plugin name="cordova.plugins.diagnostic" spec="3.7.1"/>
```

after running `cordova prepare --verbose` I get the following error output:

```
Calling plugman.fetch on plugin "cordova.plugins.diagnostic@3.7.1"
Running command: npm install cordova.plugins.diagnostic@3.7.1 --production --no-save
Command finished with error code 0: npm install,cordova.plugins.diagnostic@3.7.1,--production,--no-save
Failed to restore plugin "cordova.plugins.diagnostic" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova.plugins.diagnostic@3.7.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

I am pretty sure it isn't my connection since all other plugin dependencies (around 15 more) all succeed to install.

*Versioning:* 

```
Node version: v6.10.1
Cordova version: 7.1.0
```

If I add the plugin manually after the prepare `cordova plugin add cordova.plugins.diagnostic@3.7.1` the installation succeeds.

**Comment by dpa99c** [comment] 2017-10-27 10:01
Seems to work fine for me using the exact same config as you have (see console output below). 
You can confirm this by running the same commands in your dev environemnt.

I'm pretty sure your error is not a bug in this plugin since it is heavily used and such an issue would have been highlighted already.


<details>
<summary>console output</summary>

```

$ cordova -v
7.1.0

$ npm -v
4.2.0

$ node -v
v7.10.0

$ npm show cordova.plugins.diagnostic version
3.7.1

$ cordova create test
Creating a new cordova project.

$ cd test

$ cordova platform add android
Using cordova-fetch for cordova-android@~6.3.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the
project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~6.3.0 into config.xml file ...

$ sed -i 's/<\/widget>/<plugin name="cordova.plugins.diagnostic" spec="3.7.1"\/><\/widget>/g' config.xml

$ more config.xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="android" spec="~6.3.0" />
<plugin name="cordova.plugins.diagnostic" spec="3.7.1"/></widget>

$ sed -i 's/"dependencies": {/"dependencies": { "cordova.plugins.diagnostic": "3.7.1",/g' package.json

$ sed -i 's/"plugins": {/"plugins": { "cordova.plugins.diagnostic": {},/g' package.json

$ more package.json
{
  "name": "helloworld",
  "displayName": "HelloCordova",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": { "cordova.plugins.diagnostic": "3.7.1",
    "cordova-android": "^6.3.0",
    "cordova-plugin-whitelist": "^1.3.2"
  },
  "cordova": {
    "plugins": { "cordova.plugins.diagnostic": {},
      "cordova-plugin-whitelist": {}
    },
    "platforms": [
      "android"
    ]
  }
}

$ cordova prepare --verbose
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform android
Checking config.xml for saved plugins that haven't been added to the project
Discovered plugin "cordova.plugins.diagnostic" in config.xml. Adding it to the project
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "cordova.plugins.diagnostic@3.7.1"
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova.plugins.diagnostic@"3.7.1" --production --no-save""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova.plugins.diagnostic@"3.7.1" --production --no-save"
Copying plugin "D:\Temp\test\node_modules\cordova.plugins.diagnostic" => "D:\Temp\test\plugins\cordova.plugins.diagnostic"
Calling plugman.install on plugin "D:\Temp\test\plugins\cordova.plugins.diagnostic" for platform "android
Installing "cordova.plugins.diagnostic" for android
Running command: cmd "/s /c "D:\Temp\test\platforms\android\cordova\version.bat""
Command finished with error code 0: cmd /s /c "D:\Temp\test\platforms\android\cordova\version.bat"
Finding scripts for "before_plugin_install" hook from plugin cordova.plugins.diagnostic on android platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova.plugins.diagnostic" on android.
Beginning processing of action stack for android project...
Installing Android library: com.android.support:support-v4:26.+
Installing Android library: com.android.support:appcompat-v7:26.+
Action stack processing complete.
Updating build files since android plugin contained <framework>
Subproject Path: CordovaLib
Install complete for cordova.plugins.diagnostic on android.
Finding scripts for "after_plugin_install" hook from plugin cordova.plugins.diagnostic on android platform only.
No scripts found for hook "after_plugin_install".
No scripts found for hook "after_plugin_add".
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at D:\Temp\test\platforms\android\res\xml\config.xml
Merging project's config.xml into platform-specific android config.xml
Merging and updating files from [www, platforms\android\platform_www] to platforms\android\assets\www
  copy  platforms\android\platform_www\cordova_plugins.js platforms\android\assets\www\cordova_plugins.js (updated file)
  copy  platforms\android\platform_www\plugins\cordova.plugins.diagnostic\www\android\diagnostic.js platforms\android\assets\www\plugins\cordova.plugins.diagnostic\www\android\diagnostic.js (updated file)
Wrote out android application name "HelloCordova" to D:\Temp\test\platforms\android\res\values\strings.xml
android-versionCode not found in config.xml. Generating a code based on version in config.xml (1.0.0): 10000
Wrote out Android package name "io.cordova.hellocordova" to D:\Temp\test\platforms\android\src\io\cordova\hellocordova\MainActivity.java
This app does not have launcher icons defined
This app does not have splash screens defined
This app does not have additional resource files defined
Prepared android project successfully
No scripts found for hook "after_prepare".

$ cordova plugin ls
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova.plugins.diagnostic 3.7.1 "Diagnostic"


```

</details>

**Comment by mark-veenstra** [comment] 2017-10-27 11:02
If I create an empty project like you do and add only this plugin there is no issue.
If I downsize my own project to only use this plugin the prepare also goes alright.
I guess I have to go through all plugins to check which one creates this error with your plugin.

**Comment by dpa99c** [comment] 2017-10-27 11:05
I have found the `cordova-fetch` mechanism (the default since `cordova@7`) to be inconsistent.
When manually installing plugins, especially non-registry ones, I use `--nofetch` to use the old `git clone` mechanism which seems more reliable.

Closing this though as the issue does not lie within this plugin (it is not able to control how it is installed).

**Closed by dpa99c** 2017-10-27 11:05 UTC

**Comment by mark-veenstra** [comment] 2017-10-27 11:28
OK. I just located that if I remove 2 locally installed plugins all works fine. I will check if I can add the `--nofetch` to these locally installed plugins or maybe use `git clone` overall, guess with `cordova config set fetch false`.

Thanks for the time and effort to respond.
