### ISSUE TITLE
[BUG]Violation of Apple Store Review Guidelines

### ISSUE THREAD

**Issue by nexussmart** [dpa99c/cordova-diagnostic-plugin#316] opened 2018-07-23 17:42 UTC
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Any ios app build with the plugin can be reject at submission on the Apple Store.

Actual rejection from an app with following review:

Guideline 2.5.1 - Performance - Software Requirements

Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.

**Related code:**

I found these references in the src/ios/Diagnostic.m file @345 and @347:

#if __IPHONE_OS_VERSION_MAX_ALLOWED <= __IPHONE_8_0
            url = [NSURL URLWithString: @"prefs:root=LOCATION_SERVICES"];
#else
            url = [NSURL URLWithString: @"App-Prefs:root=Privacy&path=LOCATION"];
#endif

**Comment by dpa99c** [comment] 2018-07-24 05:48
Duplicate of #262 

Note: the code causing this issue was removed by [this commit](https://github.com/dpa99c/cordova-diagnostic-plugin/commit/7f5bae2de997345e6acfa204d4f0163d0b14912a) so is no longer present in the plugin; you can confirm this by [searching the plugin source for the offending `prefs:root`](https://github.com/search?utf8=%E2%9C%93&q=prefs%3Aroot+user%3Adpa99c+repo%3Adpa99c%2Fcordova-diagnostic-plugin+fork%3Atrue&type=Repositories&ref=advsearch&l=&l=) and see that it is no longer present.

So please update to the latest version of the plugin to resolve this.

**Closed by dpa99c** 2018-07-24 05:48 UTC
