### ISSUE TITLE
Application crashes on cold start when bluetooth is enabled

### ISSUE THREAD

**Issue by cyrus2021** [dpa99c/cordova-diagnostic-plugin#283] opened 2018-03-07 11:53 UTC
**I'm submitting a ...**  (check one with "x"):
- [ x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

On cold start of the application if devices bluetooth is on the application crashes unexpectedly.

**Expected behavior:**
Application should start up normally.

**Steps to reproduce:**

Turn on the devices **bluetooth** settings, then start up your cordova / phonegap app with this plugin installed.

**Environment information**

- Cordova CLI version 
	- `6.5.0`
- Cordova platform version
	- `android 6.3.0`
- Plugins & versions installed in project (including this plugin)
    - `com.clevertap.cordova.CleverTapPlugin 2.0.4 "CleverTap"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-fabric-plugin 1.1.13-dev "cordova-fabric-plugin"
cordova-health-walk 1.0.3 "Cordova Health Walk"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.1 "Diagnostic"`
- Dev machine OS and version, e.g.
    - OSX
        - `10.12.6`
        
_Runtime issue_
- Device details
    - Nexus 4, Motorola G2, G3, G5
- OS details
    - Android 5.0.0, Android 6.0.0, Android 7.0.0	
		
_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `cli packages: (/Users/cyrusAjency/Documents/healthwise_app/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 browser 4.1.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.5.0
    npm               : 3.10.3
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Environment Variables:

    ANDROID_HOME : /Users/cyrusAjency/Library/Android/sdk

Misc:

    backend : pro
`
- Installed Ionic Native modules and versions
    - `├── UNMET PEER DEPENDENCY @ionic-native/core@4.3.2
├── @ionic-native/diagnostic@4.5.3
├── @ionic-native/facebook@3.14.0
├── @ionic-native/health@4.5.3
├── @ionic-native/in-app-browser@4.3.2 extraneous
├── @ionic-native/native-page-transitions@4.5.3
├── @ionic-native/splash-screen@4.3.2
├── @ionic-native/status-bar@4.3.2`

![Uploading Screen Shot 2018-03-07 at 5.21.16 PM.png…]()

**Comment by dpa99c** [comment] 2018-03-07 12:17
This is a duplicate of #282

**Comment by dpa99c** [comment] 2018-03-07 12:35
Fix published in v4.0.2

**Closed by dpa99c** 2018-03-07 12:35 UTC
Labels: duplicate

**Comment by cyrus2021** [comment] 2018-03-07 13:44
ok thanks. Will check.
