### ISSUE TITLE
Getting a 'Invalid callback id received by sendPluginResult' with Xcode 7.3

### ISSUE THREAD

**Issue by theentirety** [dpa99c/cordova-diagnostic-plugin#43] opened 2016-03-26 18:16 UTC
The plugin is failing with an invalid sendPluginResult on iOS and breaks the build.

**Comment by dpa99c** [comment] 2016-03-27 08:55
> The plugin is failing with an invalid sendPluginResult on iOS and breaks the build.

An invalid plugin result would indicate a run-time error (occurring when the app is run on device/simulator) as opposed to a build error which causes the build to fail when compiling in Xcode: I'm pretty sure plugin results are not evaluated at build time.

I'm able to successfully build and run the [example project app](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on Xcode 7.3 in the following environment:

    cordova CLI 6.0.0
    cordova iOS platform 4.1.0
    XCode 7.3 (7D175)
    cordova.plugins.diagnostic@2.3.14
    
    
To help track down the error, can you post:

- the full error message and log output
- the versions of cordova CLI, cordova iOS platform and plugin you're using
- which plugin API function is causing the error
- example of the call you're making to that function, including parameter values
- whether this occurred due to upgrading the plugin (i.e. it had previously worked with another plugin version)

**Comment by dpa99c** [comment] 2016-03-29 07:26
Is this still an issue?

**Comment by theentirety** [comment] 2016-03-29 16:10
Yes, we rolled back to 2.3.11 and it is stable and works for us. You are correct it is a runtime error, not a build error. Here are the calls we make to the plugin:

```
        return new Promise((resolve, reject) => {
            cordova.plugins.diagnostic.requestMicrophoneAuthorization((status) => {
                if(status === 1) {
                    resolve(true);
                } else {
                    resolve(false);
                }
            }, reject);
        });
```

```
        return new Promise((resolve, reject) => {
            if (window.cordova) {
                cordova.plugins.diagnostic.getLocationAuthorizationStatus(status => {
                    resolve(status);
                }, reject);
            } else {
                resolve('desktop');
            }
        });
```

```
        return new Promise((resolve, reject) => {
            if (window.cordova) {
                cordova.plugins.diagnostic.isLocationEnabled(status => {
                    resolve(!!status);
                }, reject);
            } else {
                resolve(false);
            }
        });
```

I'm not sure which one is failing, but this is only failing in the simulator from Xcode or on the device with 2.3.14. I did try rolling back to 2.3.13+12 but the error persisted.

**Comment by dpa99c** [comment] 2016-03-31 08:10
I'll look into why this is when I have some time

**Comment by zedissime** [comment] 2016-04-04 09:51
I'm encountering a similar issue, except I cannot be 100% sure it cames from the plugin. 

I'm using the plugin only to check if the location is enabled :
`cordova.plugins.diagnostic.isLocationEnabled(locationSuccess, locationError);`

I'm doing this when the platform is ready, and on resume event. 
It's working well on (physical device) Android and I'm not getting any issue on the iOS emulator.
When i build & run the app on my iPhone, I'm having the white screen of death, I cannot access to the safari's console, and I'm not seeing any related log on Xcode, which is kinda complicated to debug...
I think it may be related because if I'm prefixing the use of the plugin only for Android, the app is working correctly on my iPhone.

cordova CLI 6.0.0
cordova iOS platform 4.0.1
XCode 7.2.1
cordova.plugins.diagnostic@2.3.14

**Comment by dpa99c** [comment] 2016-04-12 16:30
I'm not able to reproduce the 'Invalid callback id received by sendPluginResult' issue in the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example).

While investigating, I did spot a bug causing `getMicrophoneAuthorizationStatus()` to always return NOT_DETERMINED. This will be fixed in the next release.

@theentirety Are you able to reproduce this issue by building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example)? It calls all of the methods you've mentioned you are using. This should eliminate any bugs in your code - I believe it's possible to cause a 'Invalid callback id received by sendPluginResult' error by passing an non-function as the success callback. Because you mentioned that 2.3.11 works for you but 2.3.12 does not, but the only change between those versions is made by commit 1636f3c and this only affects `cordova.plugins.diagnostic.requestLocationAuthorization()` to make successCallback invoked in response to the user's choice in the permission dialog and to deprecate `cordova.plugins.diagnostic.registerLocationAuthorizationStatusChangeHandler ()`.

@zedissime The same applies - does the example project build and run OK?

**Comment by dpa99c** [comment] 2016-04-23 07:17
Reopen if still an issue

**Closed by dpa99c** 2016-04-23 07:17 UTC

**Comment by thor-the-norseman** [comment] 2016-05-02 13:57
I'm using your plugin through Ionic and I'm trying to call `isLocationEnabled()` and in the iOS console, it says "Invalid callback id received by sendPluginResult" and I never get a callback. My code runs inside an Angular controller "on enter" event handler and looks like this:

```
        cordova.plugins.diagnostic.isLocationEnabled(function(enabled) {
          console.log("Location enabled:", enabled);
        }, function() {
          console.log("Error"):
        });
```

My app is due to be launched tomorrow, and suddenly someone comes along and tells me that the app needs to bring people to the Location Settings screen when they have disabled their GPS, so I scramble around and find your plugin through Google, and here I am, unable to implement it.
