### ISSUE TITLE
Requesting Location authoritation on iOS getting stuck

### ISSUE THREAD

**Issue by UlisesCeca** [dpa99c/cordova-diagnostic-plugin#348] opened 2019-04-02 07:39 UTC
Hello,

If I was already prompted to allow location on iOS and I deny it, then next time that I use the requestLocationAuthorization method, it  gets stuck, doesn't go to success or error cb.

Is there a solution to this? 

Thanks.

**Comment by SpeckiJ** [comment] 2019-04-02 19:54
This is intended behaviour and caused by iOS limitations.
As the Documentation of `requestLocationAuthorization` states:

> This should only be called if authorization status is NOT_DETERMINED - calling it when in any other state will have no effect.

This limitation does not only apply to Cordova, but to all iOS Apps.

To circumvent this issue it would be easiest to handle the first time requesting the Location seperately from subsequent requests (e.g. check if your status is NOT_REQUESTED first, and then request permissions. If status is already set, you can display a hint to the user that he/she can change the permissions in the iOS Settings Menu).

**Comment by dpa99c** [comment] 2019-04-02 19:58
@SpeckiJ thanks for this very clear description. Closing this since, as you rightly state, this is a limitation of iOS, not this plugin or Cordova.

**Closed by dpa99c** 2019-04-02 19:58 UTC

**Comment by UlisesCeca** [comment] 2019-04-03 12:42
It'd be good that the plugin sends you to the error callback at least instead of getting stuck forever. That doesnt look like a right behaviour to me.

**Comment by dpa99c** [comment] 2019-04-03 12:47
In this case, the plugin [calls the native location manager](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Location.m#L84) but the location manager doesn't raise an error and never invokes the [callback delegate](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Location.m#L145) so the plugin can never know the request has not succeeded since there is no thread of execution by which it is invoked.

**Comment by Adam4224** [comment] 2020-10-12 11:08
Seems that a timeout parameter, which races a timeout against the request and then fails after the specified time would provide a better user experience than an unexpectedly hanging app.
