### ISSUE TITLE
Plugin generating raw info.plist key in Xcode

### ISSUE THREAD

**Issue by anurag0707** [dpa99c/cordova-diagnostic-plugin#310] opened 2018-06-04 12:44 UTC
**I'm submitting a
-  bug report

# Bug report

**Current behavior:**  Generating raw info.plist  **NSContactsUsageDescription**

**Expected behavior:** Should generate Xcode Key  **Privacy - Contacts Usage Description**

**Steps to reproduce:** just add the plugin and try to make a build for ios

**Environment information**

- Cordova CLI version 
	- `cordova -v` 8.0
- Cordova platform version
	- `cordova platform ls` ios@4.5.4
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls` 3.1
- Dev machine OS and version.
    - OSX
        - High Sierra 10.13.4
 
        
_Runtime issue_
- Device details
    - Generic iphone
- OS details
    - 9.0	

_iOS build issue:_
- Node JS version
    - 6.3.0
- XCode version
    -9.3.0

**Other information:**

 Just making a build for ios which automatically add NSContactsUsageDescription in *-info.plist beacuse of which I'm unable to submit my app to app store. Other key like 
     - NSContactsUsageDescription
     - Privacy - Microphone Usage Description 

is also getting generated but in Xcode key form not in raw form. Please help

**Comment by dpa99c** [comment] 2018-06-04 13:40
The [key in the plugin.xml](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L183) is correctly named as `NSContactsUsageDescription`, which is [documented by Apple](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW14).

However, if you run the `cordova prepare` operation while the iOS project is open in Xcode, the Xcode UI may not correctly pickup the changes: Xcode is not designed to have its project files externally manipulated while it's open.
If you close and re-open the project in Xcode, it should resolve the key with the correct display name. 

This is not a bug with this plugin, so closing this issue.

**Closed by dpa99c** 2018-06-04 13:40 UTC
