### ISSUE TITLE
requestRemoteNotificationAuthorization always triggers error callback on iOS during the first request

### ISSUE THREAD

**Issue by ducile** [dpa99c/cordova-diagnostic-plugin#420] opened 2020-11-02 08:59 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

When reinstalling the application and requesting remote notification permissions for the first time, the requestRemoteNotificationAuthorization function will always trigger the error callback with `Remote notifications authorization was denied` even if you accepted the request.

**Expected behavior:**

The function should go into the success callback and return the status depending on which option was chosen. 

**Steps to reproduce:**

1. Install an app with that plugin
2. Trigger the remote notification request for the first time
3. Set breakpoints in to the success and error callback
4. Accept the request 

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v 10.0.0`
- Cordova platform version
	- `cordova platform ls 6.1.1` 
- Plugins & versions installed in project (including this plugin)
```
cordova plugin ls
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
cordova-plugin-audiotoggle 1.0.3 "cordova-plugin-audiotoggle"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file-opener2 3.0.5 "File Opener2"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-iosrtc 6.0.13 "iosrtc"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-push 1.0.0 "Cordova Push Plugin"
cordova-plugin-qrscanner 3.0.1 "QRScanner"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
phonegap-plugin-multidex 1.0.0 "Multidex"
```

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers 10.15.7` 
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - iPhone X
- OS details
    -  iOS 14.1	
	
_iOS build issue:_
- Node JS version
    - `node -v 14.8.0`
- XCode version 12.1

**Related code:**
```
const iosPermissions = cordova.plugins.diagnostic;

function _requestiOSNotificationPermission(serviceDelegate) {
        return new Promise(function (resolve, reject) {
                iosPermissions.requestRemoteNotificationsAuthorization(
                        function (status) {
                            if (status === iosPermissions.permissionStatus.GRANTED) {
                                resolve();
                            } else {
                                // permission denied on ask
                                _noPermissionSnackbar(serviceDelegate, Strings.noPushPermission);

                                reject();
                            }
                        }, function (error) {
                            _noPermissionSnackbar(serviceDelegate, Strings.pushDeniedOnAppLevel);

                            reject(error);
                        },
                        [
                            iosPermissions.remoteNotificationType.ALERT,
                            iosPermissions.remoteNotificationType.SOUND,
                            iosPermissions.remoteNotificationType.BADGE
                        ]
                        , false
                    )
            }.bind(this));
    }
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment] 2020-11-02 09:47
I'm not able to reproduce this issue with the [example project app](https://github.com/dpa99c/cordova-diagnostic-plugin-example) -  tested on an iPhone 8 running iOS 14.1 and permission was requested successfully on each clean install.

Please build/run the example app and regression test using it to rule out the cause of the issue being specific to your codebase.

**Comment by ducile** [comment] 2020-11-02 12:34
I can confirm that it works fine on the example project. However, I don't really have a clue why it doesn't work in my codebase. 

I've just removed the promise wrapping as it could be a potential error case but without success. Do you have any idea where the problem might come from?

**Comment by dpa99c** [comment] 2020-11-02 12:40
I'd suggest creating a new test project to track down the cause of the issue in your project: start with just this plugin to eliminate the possibility of conflict with another plugin. Start with the simplest test case to get it working then transition it to your implementation/project to find the cause.

However closing this as you've confirmed the test project works so it's not due to a plugin bug that affects all use cases.

**Closed by dpa99c** 2020-11-02 12:40 UTC
Labels: ios, more info needed, runtime issue

**Comment by ducile** [comment] 2020-11-02 13:19
Quick update: I've found the origin of the problem. There was a second call which requested the permission synchronously and therefore wasn't visible in the debugger. That second request caused the permission request function to break.
