### ISSUE TITLE
Build Failed need help

### ISSUE THREAD

**Issue by daniele777** [dpa99c/cordova-diagnostic-plugin#280] opened 2018-03-04 07:18 UTC
Repository "https://github.com/dpa99c/cordova-diagnostic-plugin.git" checked out to git ref "master" at "0a03c35".
Installing "cordova.plugins.diagnostic" at "4.0.0" for android
Fetching plugin "cordova-plugin-whitelist@1.2.2" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Can i fix????

**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone 7, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 11.2, Android 8.1_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `ionic info`
- Installed Ionic Native modules and versions
    - `npm list | grep "@ionic-native"`

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by daniele777** [comment] 2018-03-04 08:47
https://build.phonegap.com/ i create my build here... after package create wit intel xdk

Build Date: 2018-03-04 08:46:52 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-crosswalk-webview@1.8.0" via npm
Installing "cordova-plugin-crosswalk-webview" at "1.8.0" for android
Fetching plugin "cordova-plugin-statusbar@2.2.3" via npm
Installing "cordova-plugin-statusbar" at "2.2.3" for android
Fetching plugin "cordova-plugin-device@1.1.6" via npm
Installing "cordova-plugin-device" at "1.1.6" for android
Fetching plugin "cordova-plugin-splashscreen@4.0.3" via npm
Installing "cordova-plugin-splashscreen" at "4.0.3" for android
Fetching plugin "cordova-plugin-network-information@1.3.3" via npm
Installing "cordova-plugin-network-information" at "1.3.3" for android
Fetching plugin "cordova-plugin-dialogs@1.3.3" via npm
Installing "cordova-plugin-dialogs" at "1.3.3" for android
Fetching plugin "cordova-plugin-compat@1.0.0" via npm
Installing "cordova-plugin-compat" at "1.0.0" for android
Fetching plugin "cordova-plugin-geolocation@2.4.3" via npm
Installing "cordova-plugin-geolocation" at "2.4.3" for android
Plugin dependency "cordova-plugin-compat@1.0.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on android.
Fetching plugin "cordova-plugin-globalization@1.0.7" via npm
Installing "cordova-plugin-globalization" at "1.0.7" for android
Fetching plugin "https://github.com/dpa99c/cordova-diagnostic-plugin.git" via git clone
Using shallow clone
Repository "https://github.com/dpa99c/cordova-diagnostic-plugin.git" checked out to git ref "master" at "0a03c35".
Installing "cordova.plugins.diagnostic" at "4.0.0" for android
Fetching plugin "cordova-plugin-whitelist@1.2.2" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
null
org.xwalk:xwalk_core_library:19+
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportAnimatedVectorDrawable2600Alpha1Library
:prepareComAndroidSupportAppcompatV72600Alpha1Library
:prepareComAndroidSupportSupportCompat2600Alpha1Library
:prepareComAndroidSupportSupportCoreUi2600Alpha1Library
:prepareComAndroidSupportSupportCoreUtils2600Alpha1Library
:prepareComAndroidSupportSupportFragment2600Alpha1Library
:prepareComAndroidSupportSupportMediaCompat2600Alpha1Library
:prepareComAndroidSupportSupportV42600Alpha1Library
:prepareComAndroidSupportSupportVectorDrawable2600Alpha1Library
:prepareOrgXwalkXwalk_core_library19495145Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:createXwalkCommandLineFileRelease
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources/project/build/intermediates/res/merged/release/values-v24/values-v24.xml:3 : AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/project/build/intermediates/res/merged/release/values-v24/values-v24.xml:4 : AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/opt/android-sdk/build-tools/27.0.2/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.207 secs
undefined

Thank you for help!

**Comment by daniele777** [comment] 2018-03-04 08:48
But not release apk...

**Comment by dpa99c** [comment] 2018-03-04 21:00
The cause is a Gradle version collision caused by another plugin requesting a different version of the Android Support Library (see #218, #211, #205, etc.).

The first easiest fix to try is installing [cordova-android-support-gradle-release](https://github.com/dpa99c/cordova-android-support-gradle-release) into your project to align the versions. Otherwise you'll need to manually align the version in the `build.gradle` and any other Gradle files that other plugins install.

Closing as this is not directly caused by this plugin but is an artefact of the Cordova Android build process.

**Closed by dpa99c** 2018-03-04 21:00 UTC
Labels: more info needed
