### ISSUE TITLE
Phonegap diagnostic plugin not working

### ISSUE THREAD

**Issue by mohsinali1317** [dpa99c/cordova-diagnostic-plugin#78] opened 2016-06-03 12:55 UTC
I am trying to use Phonegap plugin diagnostic but it does not work. Here is how I add it in my cnfig.xml

    <widget 
    xmlns="http://www.w3.org/ns/widgets" 
    xmlns:gap="http://phonegap.com/ns/1.0" 
    id="com.crondale.tippnett" 
    version="1.1.10">
    <name>TippNett</name>
    <description>TippNett er et system for å som bidrar til bedre massebalanse.   Systemet finner anlegg i nærheten med motsatt massebehov. Det bidrar til kortere kjørelengde og raskere anleggsutførsel. Du sparer penger, i tillegg til at miljøet blir spart for CO2 utslipp.</description>
    <author href="http://www.crondale.com" email="support@crondale.com">Crondale</author>
    <content src="index.html" />
    <access origin="*" />
    <preference name="SplashScreen" value="screen" />
    <preference name="windows-target-version" value="8.0" />
    <preference name="windows-phone-target-version" value="8.1" />
    <preference name="target-device" value="universal" />

     <platform name="android">
        <preference name="orientation" value="portrait" />
    </platform>
	
	<platform name="ios">
		<preference name="orientation" value="portrait" />
	</platform>

    <gap:plugin name="cordova-plugin-whitelist" source="npm" version="1.0.0" />
    <gap:plugin name="cordova-plugin-device" source="npm" version="1.0.1" />
    <gap:plugin name="cordova-plugin-inappbrowser" source="npm" version="1.0.1" />
    <gap:plugin name="cordova-plugin-network-information" source="npm" version="1.2.1" />
    <gap:plugin name="cordova-plugin-geolocation" source="npm"/>

    // here I add it
    <gap:plugin name="cordova.plugins.diagnostic" source="npm" />

      ....
    </widget>

Here is my code in index.js

    function onDeviceReady() {
             // Handle the Cordova pause and resume events

             alert(cordova.plugins); // I get un-define here
            cordova.plugins.diagnostic.isLocationEnabledSetting(function(enabled){
                alert(11);
            if(enabled)
            {
                alert("Location Setting is enabled");
            }
            else
            {
                alert("Location Setting is disabled");
            }
        }, function(error){
            alert("The following error occurred: "+error);
        });

I have tried it both on android and on ios as well. But I get the same result in both of them.

**Comment by dpa99c** [comment] 2016-06-03 13:33
From your `config.xml`, I assume you are building using Phonegap Build rather than locally, so it's harder to diagnose issues.

> `alert(cordova.plugins); // I get un-define here`

This would indicate the plugin is not being loaded into the Cordova app.

One possible cause is you have an invalid plugin declaration, which may be enough to cause Phonegap Build to fail installing plugins:

    <gap:plugin name="cordova plugin add cordova-plugin-geolocation" source="npm"/>

should be

    <gap:plugin name="cordova-plugin-geolocation" source="npm"/>

Also, since you're using the ([deprecated](http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#importing-config)) `<gap:plugin>` syntax to load all the other plugins, you may want to use the same when loading this one: 

    <gap:plugin name="cordova.plugins.diagnostic" source="npm" />

**Comment by mohsinali1317** [comment] 2016-06-06 05:32
I have fixed what you said but still the same issue. Kindly see the updated post to check how I am including the plugins now. Yeah I think it is failing because of the plugin loading and it is this one which is failing.

    <gap:plugin name="cordova.plugins.diagnostic" source="npm" />

If I remove it, it starts to work.

**Comment by balapkm** [comment] 2016-06-08 08:10
This plugins works fine on kitkat, not working in android 5(lolipop) while checking location enabled or not.
how to fix this ???

**Comment by dpa99c** [comment] 2016-06-09 09:31
@balapkm The issue you are reporting is not the same as this one reported by @mohsinali1317. In his case, the problem is the plugin is not being loaded into the app. You are describing a different problem, so please open a new issue. However, all of the plugin functionality including `isLocationEnabled()` has been tested and validated on Android 4, 5 and 6, so please try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to eliminate issues in your own code before opening an issue.

**Comment by dpa99c** [comment] 2016-06-09 20:26
@mohsinali1317 [Here is the APK](http://ge.tt/3m5vEIb2) from a successful build of the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) using Phonegap Build - log output as follows:

    Build Date: 2016-06-09 16:45:29 +0000
    --------------------------------------------------------------------------------
    PLUGIN OUTPUT
    --------------------------------------------------------------------------------
    Fetching plugin "cordova-plugin-whitelist@*" via npm
    Installing "cordova-plugin-whitelist" at "1.2.2" for android

                   This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
    Fetching plugin "cordova-plugin-device@*" via npm
    Installing "cordova-plugin-device" at "1.1.2" for android
    Fetching plugin "cordova-custom-config@*" via npm
    Installing "cordova-custom-config" at "2.0.0" for android
    Fetching plugin "cordova-plugin-geolocation@2.1.0" via npm
    Installing "cordova-plugin-geolocation" at "2.1.0" for android
    Fetching plugin "cordova-plugin-camera@2.1.0" via npm
    Installing "cordova-plugin-camera" at "2.1.0" for android
    Fetching plugin "cordova.plugins.diagnostic@*" via npm
    Installing "cordova.plugins.diagnostic" at "3.0.2" for android
    --------------------------------------------------------------------------------
    COMPILE OUTPUT
    --------------------------------------------------------------------------------
    :preBuild UP-TO-DATE
    :preDebugBuild UP-TO-DATE
    :checkDebugManifest
    :preReleaseBuild UP-TO-DATE
    :CordovaLib:preBuild UP-TO-DATE
    :CordovaLib:preDebugBuild UP-TO-DATE
    :CordovaLib:compileDebugNdk UP-TO-DATE
    :CordovaLib:compileLint
    :CordovaLib:copyDebugLint UP-TO-DATE
    :CordovaLib:mergeDebugProguardFiles
    :CordovaLib:packageDebugRenderscript UP-TO-DATE
    :CordovaLib:checkDebugManifest
    :CordovaLib:prepareDebugDependencies
    :CordovaLib:compileDebugRenderscript
    :CordovaLib:generateDebugResValues
    :CordovaLib:generateDebugResources
    :CordovaLib:packageDebugResources
    :CordovaLib:compileDebugAidl
    :CordovaLib:generateDebugBuildConfig
    :CordovaLib:generateDebugAssets UP-TO-DATE
    :CordovaLib:mergeDebugAssets
    :CordovaLib:processDebugManifest
    :CordovaLib:processDebugResources
    :CordovaLib:generateDebugSources
    :CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.

    :CordovaLib:processDebugJavaRes UP-TO-DATE
    :CordovaLib:transformResourcesWithMergeJavaResForDebug
    :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
    :CordovaLib:mergeDebugJniLibFolders
    :CordovaLib:transformNative_libsWithMergeJniLibsForDebug
    :CordovaLib:transformNative_libsWithSyncJniLibsForDebug
    :CordovaLib:bundleDebug
    :CordovaLib:preReleaseBuild UP-TO-DATE
    :CordovaLib:compileReleaseNdk UP-TO-DATE
    :CordovaLib:copyReleaseLint UP-TO-DATE
    :CordovaLib:mergeReleaseProguardFiles
    :CordovaLib:packageReleaseRenderscript UP-TO-DATE
    :CordovaLib:checkReleaseManifest
    :CordovaLib:prepareReleaseDependencies
    :CordovaLib:compileReleaseRenderscript
    :CordovaLib:generateReleaseResValues
    :CordovaLib:generateReleaseResources
    :CordovaLib:packageReleaseResources
    :CordovaLib:compileReleaseAidl
    :CordovaLib:generateReleaseBuildConfig
    :CordovaLib:generateReleaseAssets UP-TO-DATE
    :CordovaLib:mergeReleaseAssets
    :CordovaLib:processReleaseManifest
    :CordovaLib:processReleaseResources
    :CordovaLib:generateReleaseSources
    :CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.

    :CordovaLib:processReleaseJavaRes UP-TO-DATE
    :CordovaLib:transformResourcesWithMergeJavaResForRelease
    :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
    :CordovaLib:mergeReleaseJniLibFolders
    :CordovaLib:transformNative_libsWithMergeJniLibsForRelease
    :CordovaLib:transformNative_libsWithSyncJniLibsForRelease
    :CordovaLib:bundleRelease
    :prepareComAndroidSupportAnimatedVectorDrawable2340Library
    :prepareComAndroidSupportAppcompatV72340Library
    :prepareComAndroidSupportSupportV42340Library
    :prepareComAndroidSupportSupportVectorDrawable2340Library
    :prepareProjectCordovaLibUnspecifiedDebugLibrary
    :prepareDebugDependencies
    :compileDebugAidl
    :compileDebugRenderscript
    :generateDebugBuildConfig
    :generateDebugAssets UP-TO-DATE
    :mergeDebugAssets
    :generateDebugResValues
    :generateDebugResources
    :mergeDebugResources
    :processDebugManifest
    :processDebugResources
    :generateDebugSources
    :compileDebugJavaWithJavacNote: /project/src/cordova/plugins/Diagnostic.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.

    :compileDebugNdk UP-TO-DATE
    :compileDebugSources
    :transformClassesWithDexForDebug
    :mergeDebugJniLibFolders
    :transformNative_libsWithMergeJniLibsForDebug
    :processDebugJavaRes UP-TO-DATE
    :transformResourcesWithMergeJavaResForDebug
    :validateDebugSigning
    :packageDebug
    :zipalignDebug
    :assembleDebug
    :cdvBuildDebug

    BUILD SUCCESSFUL

    Total time: 38.848 secs
    Built the following apk(s): 
        /project/build/outputs/apk/project-debug.apk

If you install and run this APK, you will see that the plugin is loaded correctly and the app functions as expected. This validates that the plugin works fine with Phonegap Build - you can try building and running the project yourself to confirm this and post the results.

**Comment by dpa99c** [comment] 2016-06-21 07:09
Reopen if still an issue

**Closed by dpa99c** 2016-06-21 07:09 UTC
Labels: more info needed
