### ISSUE TITLE
requestLocationAuthorization too slow on Samgun Galaxy S9

### ISSUE THREAD

**Issue by NurGuz23** [dpa99c/cordova-diagnostic-plugin#285] opened 2018-03-12 12:02 UTC
Hi guys,

when I call requestLocationAuthorization, if i haven't permission, I needed accept. If I accept the request in requestLocationAuthorization  in other devices, for example S6 or S7, was good and fast. But un S9 is too slow! I think that it's and issue.

` this.diagnostic.isLocationAuthorized().then((res) => {
        if (res === false) {
          alert('Necesitas dar permisos a la aplicación: ' + res)
          this.diagnostic.requestLocationAuthorization(this.diagnostic.locationAuthorizationMode.ALWAYS).then((res) => {
            alert('here is too slow on S9: ' + res);
          });

        }
        else
          alert(res)
      });`

Any solution? 

Regards

**Comment by dpa99c** [comment] 2018-03-12 12:14
The Android runtime permissions code is carried out natively by the Android OS. This plugin has no control over how long that process takes. As you haven't filled out the issue template and supplied the necessary details such as the Android version, it's hard to speculate on the cause, but for certain it's not this plugin.
You can regression test using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin) to eliminate any bugs in your own code.

Closing this issue as there is not sufficient detail as the issue template was not completed. 
If, after testing the example project, you wish to pursue this issue, please open a new issue and complete the issue template with the required information.

**Closed by dpa99c** 2018-03-12 12:14 UTC
