### ISSUE TITLE
Android: first call to requestLocationAuthorization always returns a wrong value

### ISSUE THREAD

**Issue by samikha** [dpa99c/cordova-diagnostic-plugin#52] opened 2016-04-11 09:01 UTC
On Android, if you install the app for the first time, the first call to requestLocationAuthorization always returns GRANTED without waiting for the user choice.

I debugged this further, and turns out the 'GRANTED' is returned by mistake by combineLocationStatuses().  If I use requestRuntimePermission directly in my program, then the first call always returns 'undefined' (it correctly shows the choice dialog, but returns before the user chooses an option).  All subsequent call to requestRuntimePermissions() work properly as documented.

**Comment by dpa99c** [comment] 2016-04-12 17:18
I'm unable to reproduce these issues: running the [generic example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on Android 6.0, I'm able to see that `requestLocationAuthorization()` is correctly invoked only after the user makes a dialog choice and that the reported status is correct - if DENIED is selected, the correct status is reported in the callback.

Also, running the [Android-specific example project](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) I'm able to see that the initial call to `requestRuntimePermission()` returns the correct status in response to user choice in the dialog.

Are you able to build and run these example projects to confirm you can see the same results?

**Comment by samikha** [comment] 2016-04-13 06:56
Hi Dave, I tried the Android-specific example project and it seems to work well as you said.

Debugging things further, it seems that in my case getLocationAuthorizationStatus  is returning DENIED_ALWAYS the first time the app is installed (as opposed to NOT_REQUESTED in the android example).   If I call requestRuntimePermission afterwards, I get the dialog box and I can correctly grant the permission to the application.

**Comment by dpa99c** [comment] 2016-04-13 07:28
OK, you may be able to do a bit more debugging here... 

Ot's impossible to distinguish between NOT_REQUESTED and DENIED_ALWAYS using the native Android runtime permissions API. They both return the same constant value.

This plugin attempts to distinguish the difference by using local storage to keep track of which permissions have been requested since the app was first installed. On requesting a permission for the first time, an entry is put into local storage against the permission name. If the user then selects DENY_ALWAYS, the plugin uses the flag in local storage to distinguish this from NOT_REQUESTED.

Soo, you should be able to try this: uninstall the app and re-install (for the first time). Before requesting any permissions, use Chrome Dev Tools to remotely inspect the Cordova webview on the device/emulator. 
- Open the Resources tab and select Local Storage > file://. You should initially see no entries related to the plugin.
- Then switch to the Sources tab and browse to find the plugin script `diagnostic.js`. Place breakpoints on the functions `updateFirstRequestedPermissions` and `resolveStatus`
- Now request a runtime permission and step through with the debugger. This should indicate why DENIED_ALWAYS is being returned for the first time. Once a permission has been requested for the first time, you should see a relevant entry for its permission group appear in local storage.

**Comment by samikha** [comment] 2016-04-15 03:00
Hi,

I've tried what you suggested, but for some reason whenever I put breakpoints it always works and returns NOT_REQUESTED properly.

In my case, I have the call to check to getLocationAuthorizationStatus at the start of the application; if I comment it out, everything works. However, if I have that getLocationAuthorizationStatus at the begging in Angular's App.run, then the subsequent call to requestRuntimePermission() ends prematurely. 

Is it possible in the Android code in _requestRuntimePermissions to not check for the status of the permission before requesting them?

**Comment by samikha** [comment] 2016-05-08 17:53
Ok, after further investigation, I think this issue is due to localStorage behaving strangely.  I am using Crosswalk (I have a feeling it's related), and for some strange reasons, localStorage is partially persistent even after uninstall (I think it's stored as part of Chrome's data and not in an app specific location?). The strange thing is that this happens only in debug mode and doesn't seem to happen when compiling a release apk.

Still, regarding this plugin, I think there should be an option to never return DENIED_ALWAYS and to not use localStorage, because anyway, the behavior of 'Never ask again' is dealt with by Android and shouldn't be done in the plugin

**Comment by dpa99c** [comment] 2016-05-12 12:26
The behaviour regarding Crosswalk, this would explain the strange behaviour you observed, but this cannot be addressed by the plugin.

Regarding the disambiguation of NOT_REQUESTED vs DENIED_ALWAYS, I disagree that Android deals with this effectively. In fact, many discussions for implementing Android 6 runtime permissions natively also criticise the ambiguity of these 2 states and recommend using local persistence to disambiguate. The reason for doing so, is that the app author may want to respond very differently as to whether the permission is NOT_REQUESTED or DENIED_ALWAYS - I myself rely on this in my own apps. HTML5 local storage is the least invasive method of storing this information and other than the edge case you have observed, is pretty reliable in vanilla Cordova apps. 

But if you really want to code it as Google intended, your app can simply treat NOT_REQUESTED and DENIED_ALWAYS as the same and handle them identically. What is stored in local storage then becomes irrelevant.

**Closed by dpa99c** 2016-05-12 12:26 UTC
Labels: investigate

**Comment by avblink** [comment] 2018-01-14 21:38
The example script mentioned above returns DENIED ALWAYS on my samsung galaxy s8+

**Comment by pugwonk** [comment] 2023-01-05 21:07
I think there's still a bit of an odd problem to do with how this plugin is persisting the "DENIED_ALWAYS" flag. I don't have exactly the same problem as @samikha - my app is behaving exactly as expected in debug mode, but in release mode it is returning "DENIED_ALWAYS". This is true even if I uninstall/reinstall the app. Is it possible that somehow the "DENIED_ALWAYS" setting is persisting across reinstalls (I am not using Crosswalk, at least knowingly!)?
