### ISSUE TITLE
Android 6 (api 23) runtime permissions not asked

### ISSUE THREAD

**Issue by fastluca** [dpa99c/cordova-diagnostic-plugin#259] opened 2017-12-11 13:39 UTC
Hello,
I'm trying to ask for multiple runtime permissions on android api 23 and waiting for the user response, but it doesn't work. Maybe I'm missing something..
This is the code of my app.component.ts:
```
import { Component, ViewChild, OnInit } from '@angular/core';
import { Nav, Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { HomePage } from '../pages/home/home';
import { ListPage } from '../pages/list/list';

import { Globalization } from "@ionic-native/globalization";
import { Diagnostic } from '@ionic-native/diagnostic';


@Component({
  templateUrl: 'app.html'
})
export class MyApp implements OnInit {

  @ViewChild(Nav) nav: Nav;


  constructor(public platform: Platform, public statusBar: StatusBar, public splashScreen: SplashScreen, private globalization: Globalization,  private diagnosticNative: Diagnostic) {
    // used for an example of ngFor and navigation
    this.pages = [
      { title: 'Home', component: HomePage },
      { title: 'List', component: ListPage }
    ];

  }

  ngOnInit(): void {
    this.initializeApp();
  }

  private initializeApp() {
    console.log("App initialization");
    this.platform.ready().then(async() => {

      await this.checkPermissions();

     //other stuff is done here, involving geoposition and audio recording services


      if (this.platform.is('cordova')) {
        // Okay, so the platform is ready and our plugins are available.
        // Here you can do any higher level native things you might need.
        this.statusBar.styleDefault();
        this.splashScreen.hide();
      }

    });
  }

  /**
   * 
   */
  private async checkPermissions() {
    /*let status = await this.diagnostic.checkMicrophoneAvailability();
    console.log("Status: " + status);
    let auth = await this.diagnostic.checkLocationAvailability();
    console.log("Location is available: ", auth);*/
    let permissions: Array<any> = [
      this.diagnosticNative.permission.ACCESS_COARSE_LOCATION,
      this.diagnosticNative.permission.ACCESS_FINE_LOCATION,
      this.diagnosticNative.permission.RECORD_AUDIO
    ];
    try {
      let res = await this.diagnosticNative.requestRuntimePermissions(permissions);
      for (var permission in res) {
        switch (res[permission]) {
          case this.diagnosticNative.permissionStatus.GRANTED:
            console.log("Permission granted to use " + permission);
            break;
          case this.diagnosticNative.permissionStatus.NOT_REQUESTED:
            console.log("Permission to use " + permission + " has not been requested yet");
            break;
          case this.diagnosticNative.permissionStatus.DENIED:
            console.log("Permission denied to use " + permission + " - ask again?");
            break;
          case this.diagnosticNative.permissionStatus.DENIED_ALWAYS:
            console.log("Permission permanently denied to use " + permission + " - guess we won't be using it then!");
            break;
        }
      }
    } catch (err) {
      console.log("Err: " + err);
    }
    return true;
  }
}


```
Only a RECORD_AUDIO popup is displayed and the execution doesn't wait the user response, but continues instantiating the resources declared after the checkPermission() call.

**Comment by dpa99c** [comment] 2017-12-11 13:48
Did you ([as documented](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions)) include the necessary `<uses-permission>` keys in the `AndroidManifest.xml`?

Also see the various example projects for working illustrations of how to use this plugin:
-  [cordova-diagnostic-plugin-example](https://github.com/dpa99c/cordova-diagnostic-plugin-example)
- [cordova-diagnostic-plugin-ionic-example](https://github.com/dpa99c/cordova-diagnostic-plugin-ionic-example)
- [cordova-diagnostic-plugin-android-runtime-example](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example)

**Comment by fastluca** [comment] 2017-12-11 14:17
Sorry, I miss to report my configuration.
I've included in the file `config.xml` the following lines:
```
 <config-file parent="/*" target="AndroidManifest.xml">
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
        <uses-permission android:name="android.permission.RECORD_AUDIO" />
  </config-file>
  <engine name="android" spec="^6.3.0" />
```
Is not this sufficient?
Thank you.

**Comment by dpa99c** [comment] 2017-12-11 14:20
> Is not this sufficient?

That depends on your build environment. Did you check to see if these keys are present in your `AndroidManifest.xml`?

**Comment by fastluca** [comment] 2017-12-11 14:24
The `AndroidManifest.xml` under the path platforms/android contains the following lines at the end:
```
 <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26" />
 <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
 <uses-permission android:name="android.permission.RECORD_AUDIO" />
 <uses-permission android:name="android.permission.WAKE_LOCK" />
 <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
 <uses-permission android:name="android.permission.VIBRATE" />
 <uses-feature android:name="android.hardware.location.gps" />
```
Thanks for your time.

**Comment by dpa99c** [comment] 2017-12-11 14:46
The plugin makes internal use of `requestRuntimePermissions()`, for example [in requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L623). You can validate this works correctly by building and running [cordova-diagnostic-plugin-example](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which makes [use of it](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L167).

Additionally, you are interacting with the plugin via the [Ionic Native wrapper](https://ionicframework.com/docs/native/diagnostic/) so you may want to try interacting with the plugin's JS API directly to rule out any issue with the Typescript wrapper.

**Comment by fastluca** [comment] 2017-12-11 14:54
> Additionally, you are interacting with the plugin via the Ionic Native wrapper so you may want to try interacting with the plugin's JS API directly to rule out any issue with the Typescript wrapper.

This is interesting, but for me is the first time. Could you suggest the right way to use the plugin directly?
Thanks.

**Comment by dpa99c** [comment] 2017-12-11 15:30
cordova.plugins.diagnostic.requestRuntimePermissions((permissions) => {
        for (var permission in res) {
            switch (res[permission]) {
              case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                console.log("Permission granted to use " + permission);
                break;
              case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                console.log("Permission to use " + permission + " has not been requested yet");
                break;
              case cordova.plugins.diagnostic.permissionStatus.DENIED:
                console.log("Permission denied to use " + permission + " - ask again?");
                break;
              case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use " + permission + " - guess we won't be using it then!");
                break;
            }
          }
    }, (error) => {
        console.error(error);
    },[
        cordova.plugins.diagnostic.permission.ACCESS_COARSE_LOCATION,
        cordova.plugins.diagnostic.permission.ACCESS_FINE_LOCATION,
        cordova.plugins.diagnostic.permission.RECORD_AUDIO
    ]);

**Comment by fastluca** [comment] 2017-12-11 15:56
I will try as soon as possible and I will inform you. Thanks.

**Comment by fastluca** [comment] 2017-12-11 16:41
I tried with the following code in my `onInit` method:
```
cordova.plugins.diagnostic.requestRuntimePermissions((permissions) => {
        console.log("Permission asked: " + JSON.stringify(permissions));
        for (let permission in permissions) {
          console.log("Evaluating permission: " + permission);
          switch (permissions[permission]) {
            case cordova.plugins.diagnostic.permissionStatus.GRANTED:
              console.log("Permission granted to use " + permission);
              break;
            case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
              console.log("Permission to use " + permission + " has not been requested yet");
              break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED:
              console.log("Permission denied to use " + permission + " - ask again?");
              break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
              console.log("Permission permanently denied to use " + permission + " - guess we won't be using it then!");
              break;
          }
        }

        console.log("Start init app resources...");

    //other stuff here

        if (this.platform.is('cordova')) {
          // Okay, so the platform is ready and our plugins are available.
          // Here you can do any higher level native things you might need.
          this.statusBar.styleDefault();
          this.splashScreen.hide();
        }

      }, (error) => {
        console.error("Erros during asking for auth: " + error);
      }, [
          cordova.plugins.diagnostic.permission.ACCESS_COARSE_LOCATION,
          cordova.plugins.diagnostic.permission.ACCESS_FINE_LOCATION,
          cordova.plugins.diagnostic.permission.RECORD_AUDIO
        ]);
```
The result is that only Audio permission is asked to the user and the execution goes on. If I resume the screen on the app again, the position permission is asked, exactly as it happens with the previous implementation.
Is it possible that I'me using a plugin which is incompatible with this one? Here my cordova configuration:
![immagine](https://user-images.githubusercontent.com/11456897/33842296-6af02b26-de9a-11e7-9741-2b0873417322.png)

**Comment by dpa99c** [comment] 2017-12-11 16:45
> Is it possible that I'me using a plugin which is incompatible with this one

Possibly. I would create a new test project containing only this plugin and get that working before you integrate it into a project containing other plugins.

**Comment by fastluca** [comment] 2017-12-11 17:55
@dpa99c I'm sure that the plugin works, also with Ionic integration. I used your [cordova-diagnostic-plugin-ionic-example](https://github.com/dpa99c/cordova-diagnostic-plugin-ionic-example) and it works fine as expected. The challenge is to make it working also with the others integration.. If we're able to detect the reason of my issue, maybe I could report to the specific plugin project.

**Comment by dpa99c** [comment] 2017-12-11 18:53
One option is to try to figure out what's going on by adding some breakpoints: in the Javascript layer using Chrome Dev Tools to connect to the Webview and in the native layer using Android Studio to put some breakpoints in the Java.

Other option is to remove the plugins from your project one-by-one until the issue goes away...

**Comment by dpa99c** [comment] 2017-12-16 08:52
Closing as it's established the issue is not specific to this plugin

**Closed by dpa99c** 2017-12-16 08:52 UTC
Labels: help wanted
