### ISSUE TITLE
TypeError: Cannot read property 'diagnostic' of undefined

### ISSUE THREAD

**Issue by mkj-git** [dpa99c/cordova-diagnostic-plugin#157] opened 2016-12-01 17:22 UTC
I am using Android lollipop
cordova 6.0.0
ionic 1.7.14
diagnostic plugin 3.3.2

i am calling 
```
document.addEventListener("resume", function(){
      cordova.plugins.diagnostic.isLocationAvailable(function(available){});
}
```
whenever i do `sudo ionic run android` in my ionic app. Sometimes it work fine sometime throw error

`TypeError: Cannot read property 'diagnostic' of undefined`

**Comment by dpa99c** [comment] 2016-12-01 17:27
This is not enough information to open an issue. 

For example, what platform OS are you encountering it on - Android or iOS? What OS version? What Cordova platform version? What is the error? Can you provide the log output containing the error message? If the error is intermittent, under what circumstances does it occur? What version of the plugin are you using?

Without such information, it will not be possible to determine if there is an issue with the plugin, and therefore the issue will be closed.

**Comment by mkj-git** [comment] 2016-12-01 17:35
i added more details

**Comment by dpa99c** [comment] 2016-12-01 18:29
> TypeError: Cannot read property 'diagnostic' of undefined

This is indicative of invoking the plugin before it has been loaded. Cordova loads the Javascript elements of its components dynamically at runtime, so until the `deviceready` event has fired, there is no guarantee that a plugin has been loaded. 

The `resume` event is fired on Android when the Cordova activity is already running and is restored to the foreground. Hence, the `deviceready` event will already have been fired and the plugins loaded. Therefore I'd be surprised if the plugin namespace is undefined when the resume event is fired. Are you invoking the diagnostic plugin anywhere else in your code? Particularly, before the `deviceready` event has been fired?

**Comment by mkj-git** [comment] 2016-12-01 18:34
But to check if location is enabled or not i will have to call `cordova.plugins.diagnostic.isLocationAvailable` from multiple place so how can i dependent on `deviceready` method only. I can call it from any custom method.

I am not calling diagnostic from inside deviceready event.

**Comment by dpa99c** [comment] 2016-12-01 18:41
There is nothing wrong with calling `isLocationAvailable()` when the `resume` event is triggered, as you are doing. However, I would be surprised if this is the cause of the error you are seeing.

But, for example, if you are also calling `isLocationAvailable()` (or any other function of the plugin) before the `deviceready` event is fired, this would explain the error and the invocation should moved inside a function triggered by the `deviceready` event.

**Comment by mkj-git** [comment] 2016-12-04 06:16
I am stuck that how will I make sure that my home page controller get called only after deviceready event has been fired. cos i am calling `isLocationAvailable` inside my home page controller and there its throwing this error.

**Comment by dpa99c** [comment] 2016-12-04 09:11
Assuming you're using Ionic framework, see [this blog article](https://www.raymondcamden.com/2014/08/16/Ionic-and-Cordovas-DeviceReady-My-Solution/) for some help.

However, this isn't a problem being caused by a bug with the plugin, hence I'm closing this as an issue.

**Closed by dpa99c** 2016-12-04 09:11 UTC
Labels: awaiting response
