### ISSUE TITLE
Finger Print 

### ISSUE THREAD

**Issue by burhanfarooqws** [dpa99c/cordova-diagnostic-plugin#167] opened 2017-01-07 20:52 UTC
Hi,

I am developing app to use finger print scanner using android plugin for cordova.
The plugin failing miserably on samsung galaxy note 4.

When I used the diagnostic plugin it returns this error.
![screenshot_2017-01-08-01-46-14](https://cloud.githubusercontent.com/assets/17730402/21745068/962f8d32-d544-11e6-9dfd-6d5844c2adc7.png)

----------------------------------------------------------------------------------
below is the code i am using:
----------------------------------------------------------------------------------
// For an introduction to the Blank template, see the following documentation:
// http://go.microsoft.com/fwlink/?LinkID=397704
// To debug code on page load in Ripple or on Android devices/emulators: launch your app, set breakpoints, 
// and then run "window.location.reload()" in the JavaScript Console.
(function () {
    "use strict";

    document.addEventListener( 'deviceready', onDeviceReady.bind( this ), false );

    function onDeviceReady() {
        // Handle the Cordova pause and resume events
        document.addEventListener( 'pause', onPause.bind( this ), false );
        document.addEventListener( 'resume', onResume.bind( this ), false );
        
        // TODO: Cordova has been loaded. Perform any initialization that requires Cordova here.
        var parentElement = document.getElementById('deviceready');
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');
        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        alert(FingerprintAuth);
        cordova.plugins.diagnostic.requestRuntimePermission(function (status) {
            switch (status) {
                case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                    alert("Permission granted to use the camera");
                    break;
                case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                    alert("Permission to use the camera has not been requested yet");
                    break;
                case cordova.plugins.diagnostic.permissionStatus.DENIED:
                    alert("Permission denied to use the camera - ask again?");
                    break;
                case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                    alert("Permission permanently denied to use the camera - guess we won't be using it then!");
                    break;
            }
        }, function (error) {
            alert("The following error occurred: " + error);
        }, cordova.plugins.diagnostic.permission.USE_FINGERPRINT);
       
    };

    function onPause() {
        // TODO: This application has been suspended. Save application state here.
    };

    function onResume() {
        // TODO: This application has been reactivated. Restore application state here.
    };
} )();

Does the plugin support detecting finger print hardware permission?

**Comment by dpa99c** [comment] 2017-01-08 06:34
[`USE_FINGERPRINT`](https://developer.android.com/reference/android/Manifest.permission.html#USE_FINGERPRINT) is classified as a "normal" permission:

> Protection level: normal

Only "dangerous" level permissions are required/able to be requested at runtime and those which are "dangerous" permissions are summarised in [Table 1 of the Android Requesting Permissions guide](https://developer.android.com/guide/topics/permissions/requesting.html#perm-groups) and, as can be seen, this doesn't contain `USE_FINGERPRINT`, therefore it's not included in the [list of runtime permissions supported by the plugin](https://github.com/dpa99c/cordova-diagnostic-plugin#dangerous-runtime-permissions).

**Comment by burhanfarooqws** [comment] 2017-01-08 11:28
So how can request permission for USE_FINGERPRINT using your plugin or any other way around it.
on mobile the finger print is working fine but when calling through cordova it just failing.

I am using Samsung Galaxy Note 4 with marshmallow.

any help would be appreciated.
Thanks

**Comment by dpa99c** [comment] 2017-01-08 12:14
I don't have a device with fingerprint scanner to test this,  but you could try using [cordova-plugin-android-fingerprint-auth](https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth) which is specifically aimed at enabling fingerprint authentication in Android 6+. The plugin includes code to request runtime permission for `USE_FINGERPRINT`.

However, it seems `USE_FINGERPRINT` was initially a "dangerous" permission in Android M Preview 1 but was changed to "normal" in Preview 2 and therefore Release (see [here](https://medium.com/@juliusspencer/android-permissions-exploration-a969a356cfed#.y7aqezs8e)). 

The [official Android developer example for Fingerprint API](https://developer.android.com/samples/FingerprintDialog/src/com.example.android.fingerprintdialog/MainActivity.html#l129) also indicates that it is no longer dangerous:

> Now the protection level of USE_FINGERPRINT permission is normal instead of dangerous.

Normal permissions do not require requesting of runtime permission - they just need to be in `AndroidManifest.xml`. 

Please let me know if `cordova-plugin-android-fingerprint-auth` successfully requests runtime permission for `USE_FINGERPRINT`. If this is the case, then the Android developer documentation is wrong and `USE_FINGERPRINT` is still an "dangerous" permission requiring runtime authorization. And if that's the case, I will add support for requesting it to this plugin.

**Comment by burhanfarooqws** [comment] 2017-01-09 10:54
Thanks @dpa99c 

The issue seems to be really troubled one.
Have a look at this issue I posted on the cordova-plugin-android-fingerprint-auth github.

https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth/issues/44#issuecomment-271097205

I wonder if the mobile manufacturer is blocking the cordova plugin like this ?

**Comment by dpa99c** [comment] 2017-01-12 14:04
Basically the Note 4 doesn't support the Android Fingerprint API and that's the issue.
Closing this as the problem is not caused by this plugin.

**Closed by dpa99c** 2017-01-12 14:04 UTC
Labels: awaiting response
