### ISSUE TITLE
requestRemoteNotificationAuthorization

### ISSUE THREAD

**Issue by pyeonjaesik** [dpa99c/cordova-diagnostic-plugin#320] opened 2018-08-07 01:43 UTC
When users don't accept notification permission, user can not use push service. So If users deny notification permission by mistake, I want to call the function(-requestRemoteNotificationAuthorization) again. BUT in ios app can not call more than twice these request-permission function,right? So I instruct users go to setting and accept notification  permission. 
Although users accept permssion, users still can not use push service. 
I guess only when users accept permission at first time users can use push service.
And when users who accept permission at first time deny notification at the setting they can not use push.But  after they accept push at the setting again they can use push service

**Comment by pyeonjaesik** [comment] 2018-08-07 01:49
Then what should I do for users to use push service when they deny notificatio permission at first time and accept permission at the setting later.

**Comment by dpa99c** [comment] 2018-08-07 08:31
The behaviour you describe is the intended behaviour of iOS: Apple assumes that if a user denies notification permission, it's not because they made a mistake, it's because they never want to receive notifications from your app.
As you can see from [the code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Notifications.m), this plugin simply calls the native iOS API functions to request remote notifications permission.

However, I was unaware that if the user subsequently allows notification permission in Settings after initially denying it, that push notifications then continue to fail, but unfortunately I don't think there's anything that can be done by this plugin or any native iOS app code, since this behaviour is all internal to iOS. 
The best thing I can suggest is that you check the permission status immediately after requesting permission for the first time and if you detect the user has denied permission, you inform them they'll need to re-install the app in order to receive push notifications.

Closing this as the cause of this issue is iOS itself and there's nothing this plugin can do to workaround it.

**Closed by dpa99c** 2018-08-07 08:31 UTC

**Comment by pyeonjaesik** [comment] 2018-08-07 10:46
I got it thank you!

2018년 8월 7일 (화) 오후 5:31, Dave Alden <notifications@github.com>님이 작성:

**Comment by amanusoftware** [comment] 2018-08-10 13:53
Hi, pyeonjaesik are you still interested in background-geolocation plugin for Android? I have a license that you can use and I can sell you for $200. Let me know if you are interested.

**Comment by pyeonjaesik** [comment] 2018-08-11 12:52
Are you from transistersoft?

2018년 8월 10일 (금) 오후 10:54, amanusoftware <notifications@github.com>님이 작성:

**Comment by amanusoftware** [comment] 2018-08-24 14:25
No I'm not, I just wanted resell my license for half price. If you want talk to me, maybe it will help both of us.
